import { initReactI18next } from "react-i18next";
import i18n from "i18next";

i18n.use(initReactI18next).init({
  lng: "",
  resources: {
    english: {
      translation: {
        here: "Here you are ",
        again: "again!",
        News: "Log in",

        Updates: "Email",
        password: "Password",
        remember: "Remember me",
        forgot: "Forgot password?",
        acc: "You don’t have an account ? ",
        sign: "Sign up.",
        could: "We could give you",
        hand: "a hand",
        resets:
          "To reset your password, select the method that is most convenient for you.",
        number: "WhatsApp number",
        mail: "Email address",
        worry: " No worries, we’ll send you reset instructions.",
        reset: "Reset password",
        try: "Try",
        ok: "Okay!",
        set: "Set your new ",
        now: "password now",
        newpass: "New Pasword",
        pick: "This time, pick one that you will remember",
        but: " but not an easy one.",
        must: "Password must have at least :",
        char: "8 characters long",
        upper: "One Upper case letter",
        lower: "One lower case letter",
        onenum: "One number",
        special: "One special character",
        connewpass: "Confirm you new password",
        changepass: "Change password",
        opps: "Oops!",
        seems: "It seems that you don’t have a WhatsApp account",
        verify:
          "Verify the phone number you used in your WhatsApp account or change the reset method.",
        tryagain: "Try again",
        resetmethod: "Change reset method",
        welcome: "Welcome to",
        world: "Sphera World!",
        second: "Create your account in seconds.",
        name: "Name",
        clicks: "By clicking the button, you agree to the ",
        termsa: "Terms of Service.",
        ald: " You already have an account ?",
      },
    },
    Czhed: {
      translation: {
        here: "ها أنت مرة !",
        again: "أخرى",
        News: "تسجيل الدخول",
        Updates: "البريد الإلكتروني",
        password: "كلمة المرور",
        remember: "تذكر تفاصيل تسجيل الدخول ",
        forgot: "نسيت كلمة المرور؟ ",
        acc: "ليس لديك حساب؟ .",
        sign: "أفتح حساب",
        could: "يمكننا أن نقدم لك !",
        hand: "يد المساعدة",
        resets:
          " لإعادة تعيين كلمة المرور الخاصة بك ، حدد الطريقة الأكثر ملاءمة لك.",
        number: "رقم الواتس اب",
        mail: "البريد الإلكتروني",
        worry: "لا تقلق ، سنرسل لك تعليمات إعادة التعيين.",
        reset: "إعادة تعيين كلمة المرور",
        try: "حاول .",
        ok: "تمام!",
        set: "ضع كلمة المرور ",
        now: "الجديدة الآن",
        newpass: "كلمة المرور الجديدة",
        pick: "هذه المرة ، اختر كلمة مرور تتذكرها .",
        but: "، لكن ليست سهلة",
        must: "يجب أن تحتوي كلمة المرور على الأقل على:",
        char: "8 أحرف",
        upper: "حرف واحد كبير",
        lower: "حرف صغير واحد",
        onenum: "رقم واحد",
        special: "حرف خاص واحد ",
        connewpass: "قم بتأكيد كلمة المرور الجديدة",
        changepass: "تغيير كلمة المرور",
        opps: " واتس اب",
        seems: "يبدو أنه ليس لديك حساب",
        verify:
          "تحقق من رقم الهاتف الذي استخدمته في حساب  الواتس اب الخاص بك أو قم بتغيير طريقة إعادة التعيين.",
        tryagain: "حاول مرة أخرى",
        resetmethod: "تغيير طريقة إعادة التعيين",
        welcome: "مرحبًا بكم في ! ",
        world: "عالم سفيرا",
        second: "أنشئ حسابك في ثوانٍ.",
        name: "اسم",
        clicks: "بالنقر على الزر، فإنك توافق على . ",
        termsa: "شروط الخدمة",
        ald: "هل لديك حساب؟  ",
      },
      rtl: true,
    },
  },
  keySeparator: false,
  interpolation: { escapeValue: false },
});

export default i18n;
